#customer
sqoop job --meta-connect jdbc:hsqldb:hsql://localhost:16000/sqoop --create customerImport  -- import --connect jdbc:mysql://localhost/cdw_sapp --driver com.mysql.jdbc.Driver --query "Select ssn, concat(UCASE(SUBSTRING(FIRST_NAME, 1, 1)),LOWER(SUBSTRING(FIRST_NAME, 2))) as first_name, lower(MIDDLE_NAME) as middle_name,  concat(UCASE(SUBSTRING(LAST_NAME, 1, 1)),LOWER(SUBSTRING(LAST_NAME, 2))) as last_name, credit_card_no, concat(apt_no, ' ', street_name) as cust_street, cust_city, cust_country,cust_zip, concat(substr(cust_phone,1,3),'-',substr(cust_phone,4,4)) as cust_phone, cust_email, last_updated, cust_state from cdw_sapp_customer WHERE \$CONDITIONS" --append --incremental lastmodified --check-column last_updated --last-value '0'  --target-dir /user/cdw_sapp/cdw_sapp_customer -m 1 --fields-terminated-by ','

#creditCard
sqoop job --meta-connect jdbc:hsqldb:hsql://localhost:16000/sqoop --create creditCardImport -- import --connect jdbc:mysql://localhost/cdw_sapp --driver com.mysql.jdbc.Driver --query "select transaction_id, concat(year,LPAD(month,2,'0'), LPAD(day,2,'0')) as TimeId, credit_card_no, cust_ssn, branch_code, transaction_value, last_updated, transaction_type from cdw_sapp_creditcard WHERE \$CONDITIONS" --incremental lastmodified --check-column last_updated --last-value '0' --target-dir /user/cdw_sapp/cdw_sapp_creditcard --append --incremental lastmodified --check-column last_updated -m 1 --fields-terminated-by ','

#time
sqoop job --meta-connect jdbc:hsqldb:hsql://localhost:16000/sqoop --create timeImport -- import --connect jdbc:mysql://localhost/cdw_sapp --driver com.mysql.jdbc.Driver --query "select transaction_id, concat(year,LPAD(month,2,'0'), LPAD(day,2,'0')) as TimeId, day, month, year, last_updated, quarter(concat(year,LPAD(month,2,'0'), LPAD(day,2,'0'))) as quarter from cdw_sapp_creditcard WHERE \$CONDITIONS" --incremental lastmodified --check-column last_updated --last-value '0' --target-dir /user/cdw_sapp/cdw_sapp_time --append --incremental lastmodified --check-column last_updated -m 1 --fields-terminated-by ','

#branch
sqoop job --meta-connect jdbc:hsqldb:hsql://localhost:16000/sqoop --create branchImport -- import --connect jdbc:mysql://localhost/cdw_sapp --driver com.mysql.jdbc.Driver --query "Select branch_code, branch_name, branch_street, branch_city, branch_zip, concat('(',substr(branch_phone,1,3),')', substr(branch_phone,4,3),'-',substr(branch_phone,7)) As branch_phone, last_updated, branch_state from cdw_sapp_branch WHERE \$CONDITIONS" --append --incremental lastmodified --check-column last_updated --last-value '0' --target-dir /user/cdw_sapp/cdw_sapp_branch -m 1 --fields-terminated-by ','
